eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/
  instance:
    prefer-ip-address: true
    
    
spring:
  application:
    name: student_service
    
server:
  port: 9192